# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdDetails',
            fields=[
                ('adId', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('adTitle', models.CharField(max_length=50)),
                ('adDescription', models.CharField(max_length=200)),
                ('mediaLink', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('adminEmail', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('accessLevel', models.CharField(default='admin', editable=False, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postDate', models.DateField()),
                ('targetLocation', models.CharField(max_length=50)),
                ('adId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.AdDetails')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('accNo', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('bankName', models.CharField(max_length=50)),
                ('branchName', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BlogDetails',
            fields=[
                ('blogId', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mwdiaType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MediaType')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userEmail', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('userType', models.CharField(max_length=8)),
                ('accNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.BankDetails')),
            ],
        ),
        migrations.AddField(
            model_name='blogdetails',
            name='userEmail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Users'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advEmail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Users'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Price'),
        ),
        migrations.AddField(
            model_name='addetails',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='blogdetails',
            unique_together=set([('blogId', 'userEmail')]),
        ),
        migrations.AlterUniqueTogether(
            name='advertisement',
            unique_together=set([('adId', 'advEmail', 'postDate')]),
        ),
    ]
