# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='mwdiaType',
            new_name='mediaType',
        ),
        migrations.AddField(
            model_name='addetails',
            name='mediaType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.MediaType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addetails',
            name='mediaLink',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='accNo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='ifsc',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='users',
            name='accNo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.BankDetails'),
        ),
        migrations.AlterField(
            model_name='users',
            name='userType',
            field=models.CharField(max_length=13),
        ),
    ]
